"""
all configurable parameters of this game
"""

"""=====NAME====="""
GAME_NAME = 'PyONG'

"""=====FPS====="""
FPS = 100

"""======SCORE======"""
SCORE_SIZE = 50

"""=====WINDOW====="""
WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 800

"""=====BAR====="""
BAR_WIDTH = 0.05 * WINDOW_WIDTH
BAR_HEIGHT = 0.25 * WINDOW_HEIGHT
BAR_VELOCITY = 0.9*WINDOW_HEIGHT

"""======BALL====="""
BALL_RADIUS = int(0.015*WINDOW_WIDTH)
BALL_VELOCITY = 0.01*WINDOW_WIDTH
BALL_VELOCITY_MAX = 0.55*WINDOW_WIDTH

"""=====COLORS====="""
BACKGROUND_COLOR = (29,29,29)
BAR_COLOR = (76, 175, 80)
BALL_COLOR = (255, 235, 59)