"""
all configurable parameters of this game
"""

"""=====NAME====="""
GAME_NAME = 'PyONG'

"""=====FPS====="""
FPS = 100

"""======SCORE======"""
SCORE_SIZE = 50

"""=====WINDOW====="""
WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 800

"""=====BAR====="""
BAR_WIDTH = 0.05 * WINDOW_WIDTH
BAR_HEIGHT = 0.25 * WINDOW_HEIGHT
BAR_VELOCITY = 0.9*WINDOW_HEIGHT

"""=====PITCH====="""
BORDER_SIZE  = 8
PITCH_WIDTH  = WINDOW_WIDTH  - BORDER_SIZE
PITCH_HEIGHT = WINDOW_HEIGHT - BORDER_SIZE
PITCH_TOP = PITCH_LEFT = BORDER_SIZE

"""======BALL====="""
BALL_RADIUS = int(0.015*WINDOW_WIDTH)
BALL_SPEED = 0.7*WINDOW_WIDTH

"""=====COLORS====="""
BACKGROUND_COLOR_START = (0, 0, 0)
BACKGROUND_COLOR_END = (150, 0, 180)
BAR_COLOR = (255, 20, 147) 
BALL_COLOR = (0, 255, 255)  

